### PR TITLE
new args

### PR DESCRIPTION
**Pull request by dblooman**
Changed from 3 to 4 args.  A base URL is now needed, this will join with the second part of the URL that is specified in the regex.  There is probably a better way to do this with regex, grabbing the beginning part, at least with this way, you can be exact with your URL.

ad0b92n_460sa

### CODE REVIEW

**Comment by JakeChampion** [comment]
Running `./bin/linkey check http://www.live.bbc.co.uk/arabic http://www.live.bbc.co.uk/arabic / a.md`

And it gives outputs like:
`Status is NOT GOOD for http://www.live.bbc.co.uk/arabic/arabic/institutional/2013/05/000000_feedback_arabic`

The url is getting an extra /arabic added.

**Comment by dblooman** [comment]
The usage would be 
`./bin/linkey check http://www.live.bbc.co.uk/arabic http://www.live.bbc.co.uk /arabic a.md`

**Comment by JakeChampion** [comment]
Yep. It states in the readme it wants the baseurl... I think I'm too tired for a proper review and test :-/ I'll go through it once more now and again on the way to work in the morning, incase I've missed things.

**Comment by JakeChampion** [comment]
Could you not infer the base url from the one being passed to phantom in the argument before?

I tried passing some regex again and no dice.

`./bin/linkey check http://www.live.bbc.co.uk/arabic http://www.live.bbc.co.uk /arabic/institutional a.md` this works

`./bin/linkey check http://www.live.bbc.co.uk/arabic http://www.live.bbc.co.uk /institutional/g a.md` this doesn't

**Comment by dblooman** [comment]
I'll give it a try

**Comment by JakeChampion** [comment]
This PR enables the user to check all the links on the page, which I couldn't do with the current implementation on master. Good for the lazy :+1:

**Pull request merged**
