### PR TITLE
Updating snap.js #2

### PR DESCRIPTION
**Pull request by JakeChampion**
Fixes issue #2

### CODE REVIEW

**Comment by dblooman** [comment]
I'll admit it, I didn't give the javascript much love, a lot of copy paste

**Comment by JakeChampion** [comment]
That's cool :-) I would think about adding in the request counter logic that David thought of. This would ensure that we capture all possible links on the site, even post-loaded ones. Should I add it in this PR or make a new one?

**Comment by dblooman** [comment]
put it in this one

**Comment by JakeChampion** [comment]
Done :+1:

**Pull request merged**
